source 'https://github.com/CocoaPods/Specs.git'

target 'SPXControls', :exclusive => true do
  pod "SPXControls", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SPXControls", :path => "../"

  
end
